version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: construction-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - construction-net
    restart: unless-stopped

  neo4j:
    image: neo4j:5.13
    container_name: construction-neo4j
    ports:
      - "7474:7474"  # HTTP Browser
      - "7687:7687"  # Bolt Protocol
    environment:
      - NEO4J_AUTH=neo4j/construction123
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_server_bolt_advertised__address=:7687
      - NEO4J_server_http_advertised__address=:7474
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    networks:
      - construction-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "construction123", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: construction-backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=construction123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAX_VISION_PAGES_PER_DOC=999
      - USE_VISION_EXTRACTION=true
      - VISION_ONLY_FOR_DIAGRAMS=true
    volumes:
      - ./chroma_data:/app/chroma_data
      - ./uploads:/app/uploads
    depends_on:
      neo4j:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - construction-net
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: construction-worker
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=construction123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAX_VISION_PAGES_PER_DOC=999
      - USE_VISION_EXTRACTION=true
      - VISION_ONLY_FOR_DIAGRAMS=true
    volumes:
      - ./chroma_data:/app/chroma_data
      - ./uploads:/app/uploads
    depends_on:
      neo4j:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - construction-net
    restart: unless-stopped
    command: python -m rq worker construction-queue --url redis://redis:6379 --worker-class rq.worker.SimpleWorker

volumes:
  redis-data:
  neo4j-data:
  neo4j-logs:

networks:
  construction-net:
    driver: bridge