version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: construction-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  neo4j:
    image: neo4j:5.13
    container_name: construction-neo4j
    ports:
      - "7474:7474"  # Browser UI
      - "7687:7687"  # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/construction123
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_memory_pagecache_size=512M
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "construction123", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
  neo4j-data:
  neo4j-logs: